name: droid-arena
services:
  web:
    container_name: web
    image: mateuszmigas/droid-arena:web
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - 5173:80

  lobby-server:
    container_name: lobby-server
    image: mateuszmigas/droid-arena:lobby-server
    build:
      context: .
      dockerfile: apps/lobby-server/Dockerfile
    ports:
      - 3001:3001

  arena-server:
    container_name: arena-server
    image: mateuszmigas/droid-arena:arena-server
    build:
      context: .
      dockerfile: apps/arena-server/Dockerfile
    ports:
      - 3002:3002

#   db:
#     image: postgres
#     restart: always
#     user: postgres
#     secrets:
#       - db-password
#     volumes:
#       - db-data:/var/lib/postgresql/data
#     environment:
#       - POSTGRES_DB=example
#       - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
#     expose:
#       - 5432
#     healthcheck:
#       test: [ "CMD", "pg_isready" ]
#       interval: 10s
#       timeout: 5s
#       retries: 5
# volumes:
#   db-data:
# secrets:
#   db-password:
#     file: db/password.txt
