global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    scheme: https
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "web"
    metrics_path: /metrics
    static_configs:
      - targets: ["web:${WEB_PORT}"]

  - job_name: "lobby-server"
    metrics_path: /metrics
    static_configs:
      - targets: ["lobby-server:${LOBBY_SERVER_PORT}"]

  - job_name: "arena-server"
    metrics_path: /metrics
    static_configs:
      - targets: ["arena-server:${ARENA_SERVER_PORT}"]

  - job_name: "redis-exporter"
    static_configs:
      - targets: ["redis-exporter:9121"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

