name: droid-arena
services:
  web:
    container_name: web
    image: mateuszmigas/droid-arena:web
    restart: always
    ports:
      - ${WEB_PORT}:80
    deploy:
      resources:
        limits:
          memory: ${WEB_CONTAINER_MEMORY}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "prometheus.io/scrape=true"
      - "prometheus.io/port=80"

  lobby-server:
    container_name: lobby-server
    image: mateuszmigas/droid-arena:lobby-server
    restart: always
    ports:
      - ${LOBBY_SERVER_PORT}:3001
    environment:
      - REDIS_URL=redis://redis:6379
    deploy:
      resources:
        limits:
          memory: ${LOBBY_SERVER_MEMORY}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - redis
    labels:
      - "prometheus.io/scrape=true"
      - "prometheus.io/port=3001"
    networks:
      - internal
      - default

  arena-server:
    container_name: arena-server
    image: mateuszmigas/droid-arena:arena-server
    restart: always
    ports:
      - ${ARENA_SERVER_PORT}:3002
    deploy:
      resources:
        limits:
          memory: ${ARENA_SERVER_MEMORY}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "prometheus.io/scrape=true"
      - "prometheus.io/port=3002"

  redis:
    container_name: redis
    image: redis:7-alpine
    expose:
      - ${REDIS_PORT}
    volumes:
      - redis-data:/data
    command: >
      redis-server 
      --save 60 1 
      --loglevel warning 
      --maxmemory ${REDIS_MEMORY} 
      --maxmemory-policy allkeys-lru
    deploy:
      resources:
        limits:
          memory: ${REDIS_MEMORY}
    networks:
      - internal

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    deploy:
      resources:
        limits:
          memory: ${PROMETHEUS_MEMORY}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    user: "nobody"
    security_opt:
      - no-new-privileges:true
    networks:
      - internal

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: always
    ports:
      - ${GRAFANA_PORT}:3000
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_USERS_ALLOW_SIGN_UP=false
    deploy:
      resources:
        limits:
          memory: ${GRAFANA_MEMORY}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - prometheus
    user: "472"
    security_opt:
      - no-new-privileges:true
    networks:
      - internal
      - default

  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter:latest
    restart: always
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    deploy:
      resources:
        limits:
          memory: ${NODE_EXPORTER_MEMORY}
    user: "nobody"
    security_opt:
      - no-new-privileges:true
    networks:
      - internal

  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:latest
    restart: always
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    deploy:
      resources:
        limits:
          memory: ${CADVISOR_MEMORY}
    security_opt:
      - no-new-privileges:true
    networks:
      - internal

  redis-exporter:
    container_name: redis-exporter
    image: oliver006/redis_exporter:latest
    restart: always
    environment:
      - REDIS_ADDR=redis://redis:6379
    deploy:
      resources:
        limits:
          memory: ${REDIS_EXPORTER_MEMORY}
    networks:
      - internal

volumes:
  redis-data:
  prometheus-data:
  grafana-data: 

networks:
  internal:
    internal: true
  default:
    driver: bridge 