name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t mateuszmigas/droid-arena:web -f apps/web/Dockerfile .
          docker build -t mateuszmigas/droid-arena:lobby-server -f apps/lobby-server/Dockerfile .
          docker build -t mateuszmigas/droid-arena:arena-server -f apps/arena-server/Dockerfile .
          docker push mateuszmigas/droid-arena:web
          docker push mateuszmigas/droid-arena:lobby-server
          docker push mateuszmigas/droid-arena:arena-server

