name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker compose build
          docker push mateuszmigas/droid-arena:web
          docker push mateuszmigas/droid-arena:lobby-server
          docker push mateuszmigas/droid-arena:arena-server

      - name: Trigger Deployment Webhook
        run: |
          PAYLOAD='{"triggered_by":"${{ github.actor }}"}'
          SIGNATURE=$(echo -n "$PAYLOAD" | openssl dgst -sha256 -hmac "${{ secrets.WEBHOOK_SECRET }}" -hex | sed 's/^.* //')
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "X-Signature: sha256=$SIGNATURE" \
            -d "$PAYLOAD" \
            ${{ secrets.WEBHOOK_URL }}

